FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY ./src /app

ENV FLASK_APP=app.py
ENV FLASK_ENV=development
ENV DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@localhost:5432/fanpulse

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
